SET SQL_SAFE_UPDATES = 0;

-- Query Lassie
SELECT * FROM PERROS
WHERE Nombre = 'Lassie';

-- Query ID Mario
SELECT ID FROM CUIDADORES
WHERE Nombre = 'Mario';

-- Query Cambio de Cuidador Perros 
UPDATE PERROS
SET ID_CUIDADOR = (SELECT ID FROM CUIDADORES WHERE Nombre = 'Mario') 
WHERE Peso < 3;

-- Query La Favorita
SELECT ID FROM GUARDERIAS WHERE Nombre = 'La Favorita';

	SELECT * FROM GUARDERIAS WHERE ID = (SELECT ID FROM GUARDERIAS WHERE Nombre = 'La Favorita');

	SELECT * FROM CUIDADORES WHERE ID_GUARDERIA = (SELECT ID FROM GUARDERIAS WHERE Nombre = 'La Favorita');

	SELECT * FROM PERROS WHERE ID_GUARDERIA = (SELECT ID FROM GUARDERIAS WHERE Nombre = 'La Favorita');

SET SQL_SAFE_UPDATES = 1;

